# Generated by Django 4.2.5 on 2023-09-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя клиента')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия клиента')),
                ('client_type', models.CharField(max_length=20, verbose_name='Тип клиента')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='KG', verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('payment_type', models.CharField(default='cash', max_length=25, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('micro_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Микрорайон, ж/м, ж/к')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартира')),
                ('apartment_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подъезд')),
                ('building', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строение')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж')),
                ('block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Блок')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapps.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиента',
                'db_table': 'client_address',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100, verbose_name='Тип лида')),
                ('appeal_type', models.CharField(max_length=100, verbose_name='Тип обращения')),
                ('object_type', models.CharField(max_length=100, verbose_name='Тип обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания лида')),
                ('work_start', models.DateTimeField(verbose_name='Дата начала работ')),
                ('work_end', models.DateTimeField(verbose_name='Дата окончания работ')),
                ('address_description', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('micro_district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Микрорайон, ж/м, ж/к')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартира')),
                ('apartment_entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подъезд')),
                ('building', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строение')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж')),
                ('block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Блок')),
                ('payment_type', models.CharField(default='cash', max_length=25, verbose_name='Тип оплаты')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Сумма заказа')),
                ('lead_status', models.CharField(blank=True, default='new', max_length=25, null=True, verbose_name='Статус лида')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание')),
                ('client_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_client_address', to='crmapps.clientaddress', verbose_name='Адрес клиента')),
                ('client_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapps.client', verbose_name='Информация о клиенте')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'ЛИД',
                'verbose_name_plural': 'ЛИДЫ',
                'db_table': 'lead',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('unit', models.CharField(blank=True, default='штука', max_length=100, null=True, verbose_name='Единица измерения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за единицу')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование задачи')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание задачи')),
                ('status', models.CharField(max_length=50, verbose_name='Статус задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapps.client', verbose_name='Клиент')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapps.lead', verbose_name='Лид')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(to='crmapps.service', verbose_name='Услуга'),
        ),
    ]
